function getProductInfo() {
  const productInfo = {
    // Astaxanthin: {
    //   molecular_weight: 460,
    //   delta_g: 224.2,
    //   precursors: "accoa",
    //   precursor_delta_g_values: "-3341.2",
    //   pathway_steps: 16,
    //   precursor_coefficients: "24",
    //   atp_cost: 24.0,
    //   nadh_cost: 28.0,
    // },
    Astaxanthin: {
      molecular_weight: 596.849976,
      delta_g: 2575.9,
      precursors: "accoa",
      precursor_delta_g_values: "-3341.2",
      pathway_steps: 16,
      precursor_coefficients: "24",
      atp_cost: 24.0,
      nadh_cost: 28.0,
    },
    "1-butanol": {
      molecular_weight: 192,
      delta_g: -171.5,
      precursors: "accoa;oaa",
      precursor_delta_g_values: "-3341.2;-827.3",
      pathway_steps: 12,
      precursor_coefficients: "1;1",
      atp_cost: 2.0,
      nadh_cost: 2.0,
    },
    "1-decanol": {
      molecular_weight: 460,
      delta_g: -124.2,
      precursors: "accoa",
      precursor_delta_g_values: "-3341.2",
      pathway_steps: 10,
      precursor_coefficients: "5.0",
      atp_cost: 5.0,
      nadh_cost: 10.0,
    },
    AKG: {
      molecular_weight: 192,
      delta_g: -828.1,
      precursors: "akg",
      precursor_delta_g_values: "-828.1",
      pathway_steps: "0",
      precursor_coefficients: "1",
      atp_cost: "0",
      nadh_cost: "0",
    },
    Acetate: {
      molecular_weight: 410,
      delta_g: -393.8,
      precursors: "pyr",
      precursor_delta_g_values: "-483.6",
      pathway_steps: 2,
      precursor_coefficients: "1",
      atp_cost: "0.0",
      nadh_cost: -1.0,
    },
    Alkanes: {
      molecular_weight: 192,
      delta_g: 77.0,
      precursors: "accoa",
      precursor_delta_g_values: "-3341.2",
      pathway_steps: 11,
      precursor_coefficients: "8.2",
      atp_cost: 8.0,
      nadh_cost: 17.0,
    },
    Amorphadiene: {
      molecular_weight: 118,
      delta_g: 161.4,
      precursors: "accoa",
      precursor_delta_g_values: "-3341.2",
      pathway_steps: 10,
      precursor_coefficients: "9",
      atp_cost: 9.0,
      nadh_cost: 6.0,
    },
    "Arachidonic acid": {
      molecular_weight: 863,
      delta_g: 61.6,
      precursors: "accoa",
      precursor_delta_g_values: "-3341.2",
      pathway_steps: 13,
      precursor_coefficients: "10.0",
      atp_cost: 9.0,
      nadh_cost: 21.0,
    },
    Arbutin: {
      molecular_weight: 192,
      delta_g: -1004.4,
      precursors: "e4p;pep;g6p",
      precursor_delta_g_values: "-1486.1;-1324.8;-1805.2",
      pathway_steps: 8,
      precursor_coefficients: "1;2;1",
      atp_cost: 2.0,
      nadh_cost: 2.0,
    },
    Betulin: {
      molecular_weight: 536,
      delta_g: -41.2,
      precursors: "accoa",
      precursor_delta_g_values: "-3341.2",
      pathway_steps: 13,
      precursor_coefficients: "18",
      atp_cost: 18.0,
      nadh_cost: 15.0,
    },
    "Betulinic acid": {
      molecular_weight: 536,
      delta_g: -245.8,
      precursors: "accoa",
      precursor_delta_g_values: "-3341.2",
      pathway_steps: 13,
      precursor_coefficients: "18",
      atp_cost: 18.0,
      nadh_cost: 17.0,
    },
    Campersterol: {
      molecular_weight: 536,
      delta_g: 68.8,
      precursors: "accoa",
      precursor_delta_g_values: "-3341.2",
      pathway_steps: 25,
      precursor_coefficients: "18",
      atp_cost: 18.0,
      nadh_cost: 31.0,
    },
    Canthaxanthin: {
      molecular_weight: 871,
      delta_g: 564.8,
      precursors: "accoa",
      precursor_delta_g_values: "-3341.2",
      pathway_steps: 15,
      precursor_coefficients: "24",
      atp_cost: 24.0,
      nadh_cost: 24.0,
    },
    Citrate: {
      molecular_weight: 192,
      delta_g: -1238.0,
      precursors: "cit",
      precursor_delta_g_values: "-1238",
      pathway_steps: "0",
      precursor_coefficients: "1",
      atp_cost: "0",
      nadh_cost: "0",
    },
    "Crotonic acid": {
      molecular_weight: 192,
      delta_g: -291.3,
      precursors: "accoa",
      precursor_delta_g_values: "-3341.2",
      pathway_steps: 4,
      precursor_coefficients: "2",
      atp_cost: "0",
      nadh_cost: 1.0,
    },
    "Decanoic Acid": {
      molecular_weight: 460,
      delta_g: -330.0,
      precursors: "accoa",
      precursor_delta_g_values: "-3341.2",
      pathway_steps: 8,
      precursor_coefficients: "5.0",
      atp_cost: 4.0,
      nadh_cost: 8.0,
    },
    Echinenone: {
      molecular_weight: 192,
      delta_g: 711.7,
      precursors: "accoa",
      precursor_delta_g_values: "-3341.2",
      pathway_steps: 14,
      precursor_coefficients: "24",
      atp_cost: 24.0,
      nadh_cost: 22.0,
    },
    Eriodictyol: {
      molecular_weight: 118,
      delta_g: -876.1,
      precursors: "accoa;e4p;pep",
      precursor_delta_g_values: "-3341.2;-1486.1;-1324.8",
      pathway_steps: 11,
      precursor_coefficients: "3;1;2",
      atp_cost: 5.0,
      nadh_cost: 2.0,
    },
    Erythritol: {
      molecular_weight: 192,
      delta_g: -641.5,
      precursors: "e4p",
      precursor_delta_g_values: "-1486.1",
      pathway_steps: 2,
      precursor_coefficients: "1",
      atp_cost: "0",
      nadh_cost: -1.0,
    },
    FAEE: {
      molecular_weight: 60,
      delta_g: -247.4,
      precursors: "accoa",
      precursor_delta_g_values: "-3341.2",
      pathway_steps: 10,
      precursor_coefficients: "9.5",
      atp_cost: 9.0,
      nadh_cost: 17.0,
    },
    FFA: {
      molecular_weight: 536,
      delta_g: -212.8,
      precursors: "accoa",
      precursor_delta_g_values: "-3341.2",
      pathway_steps: 7,
      precursor_coefficients: "8.7",
      atp_cost: 8.0,
      nadh_cost: 15.0,
    },
    "Fatty Alcohol": {
      molecular_weight: 192,
      delta_g: -82.4,
      precursors: "accoa",
      precursor_delta_g_values: "-3341.2",
      pathway_steps: 10,
      precursor_coefficients: "8.8",
      atp_cost: 9.0,
      nadh_cost: 18.0,
    },
    Fumarate: {
      molecular_weight: 846,
      delta_g: -643.7,
      precursors: "fum",
      precursor_delta_g_values: "-643.7",
      pathway_steps: "0",
      precursor_coefficients: "1",
      atp_cost: "0",
      nadh_cost: "0",
    },
    Glycogen: {
      molecular_weight: 442,
      delta_g: -2915.6,
      precursors: "g6p",
      precursor_delta_g_values: "-1805.2",
      pathway_steps: 3,
      precursor_coefficients: "4",
      atp_cost: 4.0,
      nadh_cost: "0",
    },
    Hexadecanol: {
      molecular_weight: 460,
      delta_g: -82.4,
      precursors: "accoa",
      precursor_delta_g_values: "-3341.2",
      pathway_steps: 10,
      precursor_coefficients: "8.0",
      atp_cost: 8.0,
      nadh_cost: 16.0,
    },
    Isocitrate: {
      molecular_weight: 192,
      delta_g: -1230.7,
      precursors: "icit",
      precursor_delta_g_values: "-1230.7",
      pathway_steps: "0",
      precursor_coefficients: "1",
      atp_cost: "0",
      nadh_cost: "0",
    },
    LCDCA: {
      molecular_weight: 88,
      delta_g: -1230.7,
      precursors: "accoa",
      precursor_delta_g_values: "-3341.2",
      pathway_steps: 8,
      precursor_coefficients: "8.3",
      atp_cost: 7.0,
      nadh_cost: 14.0,
    },
    Limonene: {
      molecular_weight: 126,
      delta_g: 120.9,
      precursors: "accoa",
      precursor_delta_g_values: "-3341.2",
      pathway_steps: 10,
      precursor_coefficients: "6",
      atp_cost: 6.0,
      nadh_cost: 4.0,
    },
    Linalool: {
      molecular_weight: 118,
      delta_g: 30.6,
      precursors: "accoa",
      precursor_delta_g_values: "-3341.2",
      pathway_steps: 9,
      precursor_coefficients: "6",
      atp_cost: 6.0,
      nadh_cost: 4.0,
    },
    Lipids: {
      molecular_weight: 870,
      delta_g: -203.2,
      precursors: "accoa;dhap",
      precursor_delta_g_values: "-3341.2;-1337.2",
      pathway_steps: 12,
      precursor_coefficients: "26.4352941176471;1",
      atp_cost: 23.4,
      nadh_cost: 46.9,
    },
    Lupeol: {
      molecular_weight: 536,
      delta_g: 115.9,
      precursors: "accoa",
      precursor_delta_g_values: "-3341.2",
      pathway_steps: 12,
      precursor_coefficients: "18",
      atp_cost: 18.0,
      nadh_cost: 14.0,
    },
    Lycopene: {
      molecular_weight: 204,
      delta_g: 1274.7,
      precursors: "accoa",
      precursor_delta_g_values: "-3341.2",
      pathway_steps: 12,
      precursor_coefficients: "24",
      atp_cost: 24.0,
      nadh_cost: 20.0,
    },
    Malate: {
      molecular_weight: 192,
      delta_g: -887.9,
      precursors: "mal",
      precursor_delta_g_values: "-887.9",
      pathway_steps: "0",
      precursor_coefficients: "1",
      atp_cost: "0",
      nadh_cost: "0",
    },
    Mannitol: {
      molecular_weight: 442,
      delta_g: -943.8,
      precursors: "f6p",
      precursor_delta_g_values: "-1802.7",
      pathway_steps: 2,
      precursor_coefficients: "1",
      atp_cost: "0",
      nadh_cost: 1.0,
    },
    "Methyl-ketones": {
      molecular_weight: 564,
      delta_g: 1119.8,
      precursors: "accoa",
      precursor_delta_g_values: "-3341.2",
      pathway_steps: 12,
      precursor_coefficients: "8.0",
      atp_cost: 8.0,
      nadh_cost: 13.0,
    },
    Mevalonate: {
      molecular_weight: 270,
      delta_g: -647.6,
      precursors: "accoa",
      precursor_delta_g_values: "-3341.2",
      pathway_steps: 3,
      precursor_coefficients: "3",
      atp_cost: "0",
      nadh_cost: 2.0,
    },
    Naringenin: {
      molecular_weight: 192,
      delta_g: -672.9,
      precursors: "accoa;e4p;pep",
      precursor_delta_g_values: "-3341.2;-1486.1;-1324.8",
      pathway_steps: 10,
      precursor_coefficients: "3;1;2",
      atp_cost: 5.0,
      nadh_cost: 1.0,
    },
    Nootkatone: {
      molecular_weight: 442,
      delta_g: 60.2,
      precursors: "accoa",
      precursor_delta_g_values: "-3341.2",
      pathway_steps: 11,
      precursor_coefficients: "9",
      atp_cost: 9.0,
      nadh_cost: 7.0,
    },
    Octadecanol: {
      molecular_weight: 460,
      delta_g: -28.4,
      precursors: "accoa",
      precursor_delta_g_values: "-3341.2",
      pathway_steps: 10,
      precursor_coefficients: "9.0",
      atp_cost: 9.0,
      nadh_cost: 18.0,
    },
    PHB: {
      molecular_weight: 192,
      delta_g: -529.1,
      precursors: "accoa",
      precursor_delta_g_values: "-3341.2",
      pathway_steps: 3,
      precursor_coefficients: "2",
      atp_cost: "0",
      nadh_cost: 1.0,
    },
    Pentane: {
      molecular_weight: 122,
      delta_g: 9.3,
      precursors: "accoa",
      precursor_delta_g_values: "-3341.2",
      pathway_steps: 9,
      precursor_coefficients: "9",
      atp_cost: 8.0,
      nadh_cost: 16.0,
    },
    Pregnenolone: {
      molecular_weight: 118,
      delta_g: -109.6,
      precursors: "accoa",
      precursor_delta_g_values: "-3341.2",
      pathway_steps: 28,
      precursor_coefficients: "18",
      atp_cost: 18.0,
      nadh_cost: 31.0,
    },
    Protopanaxadiol: {
      molecular_weight: 192,
      delta_g: -444.9,
      precursors: "accoa",
      precursor_delta_g_values: "-3341.2",
      pathway_steps: 13,
      precursor_coefficients: "18",
      atp_cost: 18.0,
      nadh_cost: 15.0,
    },
    Pyruvate: {
      molecular_weight: 192,
      delta_g: -483.6,
      precursors: "pyr",
      precursor_delta_g_values: "-483.6",
      pathway_steps: "0",
      precursor_coefficients: "1",
      atp_cost: "0",
      nadh_cost: "0",
    },
    Reservatrol: {
      molecular_weight: 192,
      delta_g: -254.4,
      precursors: "accoa;e4p;pep",
      precursor_delta_g_values: "-3341.2;-1486.1;-1324.8",
      pathway_steps: 10,
      precursor_coefficients: "3;1;2",
      atp_cost: 5.0,
      nadh_cost: 1.0,
    },
    Riboflavin: {
      molecular_weight: 148,
      delta_g: -524.2,
      precursors: "ru5p",
      precursor_delta_g_values: "-1640.9",
      pathway_steps: 6,
      precursor_coefficients: "1",
      atp_cost: 1.0,
      nadh_cost: 1.0,
    },
    Squalene: {
      molecular_weight: 460,
      delta_g: 646.0,
      precursors: "accoa",
      precursor_delta_g_values: "-3341.2",
      pathway_steps: 10,
      precursor_coefficients: "18",
      atp_cost: 18.0,
      nadh_cost: 12.0,
    },
    Succinate: {
      molecular_weight: 442,
      delta_g: -731.1,
      precursors: "succ",
      precursor_delta_g_values: "-731.1",
      pathway_steps: "0",
      precursor_coefficients: "1",
      atp_cost: "0",
      nadh_cost: "0",
    },
    Taxifolin: {
      molecular_weight: 118,
      delta_g: -1046.3,
      precursors: "accoa;e4p;pep",
      precursor_delta_g_values: "-3341.2;-1486.1;-1324.8",
      pathway_steps: 12,
      precursor_coefficients: "3;1;2",
      atp_cost: 5.0,
      nadh_cost: 2.0,
    },
    "Triacetic acid lactone": {
      molecular_weight: 126,
      delta_g: -134.4,
      precursors: "accoa",
      precursor_delta_g_values: "-3341.2",
      pathway_steps: 2,
      precursor_coefficients: "3",
      atp_cost: 2.0,
      nadh_cost: "0",
    },
    Valencene: {
      molecular_weight: 442,
      delta_g: 207.2,
      precursors: "accoa",
      precursor_delta_g_values: "-3341.2",
      pathway_steps: 10,
      precursor_coefficients: "9",
      atp_cost: 9.0,
      nadh_cost: 6.0,
    },
    "a-Farnesene": {
      molecular_weight: 126,
      delta_g: 386.3,
      precursors: "accoa",
      precursor_delta_g_values: "-3341.2",
      pathway_steps: 10,
      precursor_coefficients: "9",
      atp_cost: 9.0,
      nadh_cost: 6.0,
    },
    "a-Ionone": {
      molecular_weight: 564,
      delta_g: 18.3,
      precursors: "accoa",
      precursor_delta_g_values: "-3341.2",
      pathway_steps: 14,
      precursor_coefficients: "24",
      atp_cost: 24.0,
      nadh_cost: 20.0,
    },
    "a-Linolenic acid": {
      molecular_weight: 146,
      delta_g: -33.8,
      precursors: "accoa",
      precursor_delta_g_values: "-3341.2",
      pathway_steps: 10,
      precursor_coefficients: "9.0",
      atp_cost: 8.0,
      nadh_cost: 17.0,
    },
    "a-Santalene": {
      molecular_weight: 118,
      delta_g: 163.3,
      precursors: "accoa",
      precursor_delta_g_values: "-3341.2",
      pathway_steps: 10,
      precursor_coefficients: "9",
      atp_cost: 9.0,
      nadh_cost: 6.0,
    },
    "b-Carotene": {
      molecular_weight: 536,
      delta_g: 858.7,
      precursors: "accoa",
      precursor_delta_g_values: "-3341.2",
      pathway_steps: 13,
      precursor_coefficients: "24",
      atp_cost: 24.0,
      nadh_cost: 20.0,
    },
    "b-Ionone": {
      molecular_weight: 88,
      delta_g: -37.7,
      precursors: "accoa",
      precursor_delta_g_values: "-3341.2",
      pathway_steps: 14,
      precursor_coefficients: "24",
      atp_cost: 24.0,
      nadh_cost: 20.0,
    },
  };

  return productInfo;
}

export { getProductInfo };
